In [20]:
import matplotlib.pyplot as plt
import pandas as pd
import pylab as pl
import numpy as np
%matplotlib inline

In [21]:
df = pd.read_csv('data.csv')
df.head()

,کد ملک,تاریخ اپلود,نوع ملک,آدرس,نوع معامله,قیمت واحد,قیمت کل,طبقه,خواب,زیربنا,تلفن,آشپزخانه,سرویس,کفپوش
0,10134566,1403/05/17,آپارتمان,امیرآباد كارگر شمالی,خرید,"132,352,000","13,500,000,000",2.0,2.0,102.0,1,MDF,ايراني فرنگي,سراميک
1,10322202,1403/05/17,آپارتمان,هروی ساقدوش,خرید,"121,739,000","14,000,000,000",2.0,2.0,115.0,1,MDF,ايراني فرنگي,سنگ
2,10332497,1403/05/17,مستغلات,كردستان خ جانبازان,خرید,"285,000,000","114,000,000,000",NaN,8.0,440.0,1,MDF,ايرانی,سراميک
3,10354953,1403/05/17,کلنگی,ولیعصر تقاطع بهشتی,خرید,"584,795,000","100,000,000,000",NaN,0.0,150.0,0,نا مشخص,نامشخص,نا مشخص
4,10176889,1403/05/17,مغازه,گیشا خ جواد فاضل,خرید,"1,000,000,000","13,000,000,000",NaN,0.0,13.0,1,نا مشخص,ايرانی,سنگ

In [15]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
# حذف سطرهایی که حاوی مقادیر NaN یا "نامشخص" هستند
df_cleaned = df.dropna()
df_cleaned = df_cleaned[~df_cleaned.isin(['نا مشخص', 'نامشخص']).any(axis=1)]

# استخراج محله از آدرس (کلمه‌ی اول آدرس)
df_cleaned['محله'] = df_cleaned['آدرس'].apply(lambda x: x.split()[0])

# انتخاب ویژگی‌ها و هدف (قیمت واحد)
cdf = ['محله', 'طبقه', 'خواب', 'زیربنا', 'تلفن', 'آشپزخانه', 'سرویس', 'کفپوش', 'قیمت واحد']
cdf = df_cleaned[cdf]

cdf

,محله,طبقه,خواب,زیربنا,تلفن,آشپزخانه,سرویس,کفپوش,قیمت واحد
0,امیرآباد,2.0,2.0,102.0,1,MDF,ايراني فرنگي,سراميک,"132,352,000"
1,هروی,2.0,2.0,115.0,1,MDF,ايراني فرنگي,سنگ,"121,739,000"
7,جمالزاده,4.0,1.0,44.0,1,MDF,ايرانی,سراميک,"102,272,000"
8,بزرگراه,3.0,2.0,90.0,1,MDF,ايراني فرنگي,سراميک,"100,000,000"
9,شیخ,3.0,3.0,181.0,1,MDF,فرنگی,سراميک,"150,000,000"
...,...,...,...,...,...,...,...,...,...
26254,وحیدیه,4.0,2.0,62.0,1,MDF,ايرانی,سراميک,"50,000,000"
26255,فرمانیه,3.0,2.0,121.0,1,هایگلاس,ايراني فرنگي,سنگ,"255,000,000"
26256,هنگام,2.0,1.0,50.0,1,MDF,ايرانی,موزائيک,"35,000,000"
26258,جیحون,3.0,2.0,65.0,1,MDF,ايراني فرنگي,سراميک,"73,846,000"
26259,تهرانپارس,5.0,2.0,73.0,1,MDF,ايراني فرنگي,سراميک,"80,000,000"

In [24]:
msk = np.random.rand(len(cdf)) < 0.8
train = cdf[msk]
test = cdf[~msk]

In [28]:
import pandas as pd

# فرض بر این است که df_cleaned دیتافریم تمیز شده است

# استخراج لیست محله‌های غیرتکراری
unique_neighborhoods = df_cleaned['محله'].unique()

# نمایش لیست محله‌های غیرتکراری
print("Unique neighborhoods:", unique_neighborhoods)
print("Total unique neighborhoods:", len(unique_neighborhoods))

Unique neighborhoods: [190 149 236 205  56 130 176  57  70 184 228 162  62  74 101 123  30 221
 266 143  25 174 253  50 107  71  48  53 115 240 129 224  41   2 234 255
  19  21  60  47   8 195 206 259  44  88 139  24 267 169  45 239 212 231
 232 219 125 157  33 262 257 128 117  32  16  12 146 226  73 185  76  90
  91 155  17 217 142 132 249  51 138 147 177 151 150 216 261  42 189 247
  55 182  92  23  95 197 100   4 153 166  75  94  58 268 269  52 103 258
  68 215  54  82   9  65 202 161 248 114  64  80 196 116 173   7 160  99
 230 122 242 193  72 243 106 124 233  10 145 209 137 168 110   3  87 199
 265 134 238  97 140  86 159 235  59 210 179 180 120 218 131  96  83 172
  18 211 186 214  34 163 251  39   1  69  27 104 198 154  29  93 203 188
 241  14 207 102   6  79  89 192 165 175 178  15 141  11 252  28 152  26
 187   5 148 158  36 222  66 113 244  35 133 118 111 127 229  63 201 156
  40 135  98  31 263 200 164   0  77 254  78  61 194 121 237 220 204 109
 245 264 213  13 225 250 208 191  37 256 183  22  67 144 112 223 246 126
  81 167 105  49 260 171 181 108  38 227 119  85  43  20  84  46 170 136]
Total unique neighborhoods: 270

In [ ]:
from sklearn import preprocessing
le_sex = preprocessing.LabelEncoder()
le_sex.fit(['F','M'])
X[:,1] = le_sex.transform(X[:,1]) 


le_BP = preprocessing.LabelEncoder()
le_BP.fit([ 'LOW', 'NORMAL', 'HIGH'])
X[:,2] = le_BP.transform(X[:,2])


le_Chol = preprocessing.LabelEncoder()
le_Chol.fit([ 'NORMAL', 'HIGH'])
X[:,3] = le_Chol.transform(X[:,3]) 

X[0:5]